name:
  view update: codigo
table:
  search: operacion__contrato_search
scenarios:
  default: delegacion_id estado cliente tipo_contrato tipo_tarifa tipo_id
  search: codigo delegacion_nombre tipo_contrato fecha_entrega fecha_recogida tipo_id cliente estado
relations:
  detalles:
    scenario: contrato
  detalles@view:
    scenario: contratoview
sections:
  tarifas@view:
    relation: tarifas
    view: operacion/views/orden/tarifas
  detalles:
    relation: detalles
  vehiculo:
  observacion-contrato:
    relation: observacion
attributes:
  tipo_id:
    relation:
      name: 'php:"( $this->id ) $this->nombre"'
  delegacion_id:
    value: delegacion.nombre
  tipo_contrato@search:
    value: old:tipo_contrato
  estado:
    options:
      container:
        class: col-12 col-md-6 offset-lg-4 col-lg-4
  cliente:
    options:
      container:
        class: col-12
