---
name: Control de acceso
icon: fa-expeditedssl
controllers:
  default:
  user:
    name: Usuario
    icon: fa-user
  role:
    name: Rol
    icon: fa-users
  profile:
    name: Perfil
    icon: fa-universal-access
...