---
permission:
  profile__id: smallint(3) PK FK[backend__profile.id,cascade,cascade] NN UN
  route: varchar(120) PK NN
  actions: varchar(255)
profile:
  id: smallint(4) PK NN UN AI
  name: varchar(100) NN
  is_active: bit(1) NN default[1]
role:
  id: tinyint(3) PK NN UN AI
  name: varchar(60) UQ[name] NN
  is_active: bit(1) NN default[1]
role_profile:
  role__id: tinyint(3) PK FK[backend__role.id,cascade,cascade] NN UN
  profile__id: smallint(4) PK FK[backend__profile.id,cascade,cascade] NN UN
user_role:
  role__id: tinyint(3) PK FK[backend__role.id,cascade,cascade] NN UN
  user__id: smallint(5) PK FK[backend__user.id,cascade,cascade] NN UN
user:
  id: smallint(5) PK NN UN AI
  username: varchar(15) UQ[username] NN
  group: enum(ADMIN,USER,ROOT) NN
  name: varchar(120)
  email: varchar(90) UQ[email]
  password: varchar(60)
  token: varchar(36)
  status: set(VERIFED,DISABLED,BANNED) NN
...
