controllers:
  cliente: ~
  conductor: ~
  delegacion: ~
  oficina: ~
  persona: ~
  persona-contacto: ~
  persona-direccion: ~
navbar:
  order: 5
  links:
    -
      delegacion: ~
    -
      oficina: ~
