rules:
-   safe: username, name, email, group, roles, status
    scenario: search
-   safe: username, name, email, group, roles, token, status 
    scenario: view
-   safe: username, name, email, group, roles, token, status
    scenario: insert, update
-   unsafe: token, status
    scenario: insert
-   required: username, name, email, group
    scenario: insert, update
-   length: username
    min: 4
    max: 16
    scenario: insert, update
-   match: username
    pattern: /^[a-z0-9\.\_]+$/i
    scenario: insert, update
-   email: email
    scenario: insert, update
-   safe: token
    scenario: upgrade
attributes:
    token@update:
        template: <div class="input-group">{input}<span class="input-group-addon">{button}</span></div>
        params:
            button: <a class="fa fa-recycle" onclick="var $target = this.parentNode.previousSibling; $.get(createUrl('upgrade/' + $get['id'])).done(function(d){$($target).text(d)});"></a>
sections:
    base:
        title: false
        layout: false
        elements: null