controllers:
  marca: ~
  modelo: ~
  vehiculo: ~
navbar:
  order: 1
  links:
    -
      vehiculo: ~
    -
      itv: '#'
    - separator
    -
      planeacion: /flota
    -
      mantenimiento: false
    -
      marca: ~
    -
      modelo: ~
    -
      familia: false
    -
      tipo: ~
    - separator
    -
      tarifas: false
