controllers:
  marca: ~
  modelo: ~
  tipo: ~
  vehiculo: ~
  tarifa: ~
  tarifa-historico: ~
  vehiculo-movimiento: ~
  tarifa-historia: ~
navbar:
  links:
    -
      vehiculo: ~
    -
      itv: false
    - separator
    -
      planeacion: false
    -
      mantenimiento: false
    -
      marca: ~
    -
      modelo: ~
    -
      familia: false
    -
      tipo: ~
    - separator
    -
      tarifa: ~
