controllers:
  marca: ~
  modelo: ~
  tipo: ~
  vehiculo: ~
  modelo-caracteristicas: ~
  modelo-carga: ~
  vehiculo-caracteristicas: ~
navbar:
  links:
    -
      vehiculo: ~
    -
      itv: '#'
    - separator
    -
      planeacion: ~
    -
      mantenimiento: false
    -
      marca: ~
    -
      modelo: ~
    -
      familia: false
    -
      tipo: ~
    - separator
    -
      tarifas: false
