controllers: null
navbar:
  order: 1
  links:
    -
      vehiculo: null
    -
      itv: '#'
    - separator
    -
      planeacion: null
    -
      mantenimiento: false
    -
      marca: null
    -
      modelo: null
    -
      familia: null
    -
      tipo: null
    - separator
    -
      tarifas: false
