controllers:
  marca: ~
  modelo: ~
  tipo: ~
  vehiculo: ~
navbar:
  links:
  - vehiculo:
  - itv: "#"
  - separator
  - planeacion:
  - mantenimiento: false
  - marca: 
  - modelo: 
  - familia: false 
  - tipo: 
  - separator
  - tarifas: false
  
