language: es
components:
  request:
    cookieValidationKey: 5d7cff7c24278171c8044ef8f5301014
  db:
    dsn: 'mysql:host=localhost;dbname=viajes'
    username: root
    password: root
    charset: utf8
  webapp:
    class: yii\db\Connection
    dsn: 'mysql:host=localhost;dbname=webapp'
    username: root
    password: root
    charset: utf8
  view:
    theme: themes\bootstrap\Theme
params:
  admin:
    name: Admin
    email: admin@mail.com