---
aliases:
  bower: '@vendor/bower-asset'
  npm: '@vendor/npm-asset'
components:
  foo:
    class: yii\db\Connection
    dsn: mysql:host=localhost;dbname=hola
    username: root
    password: root
...
