name: IBERFURGO
language: es
components:
  request:
    cookieValidationKey: 5d7cff7c24278171c8044ef8f5301014
  formatter:
    dateFormat: php:d/m/Y
    datetimeFormat: php:d/m/Y H:i
    timeFormat: php:H:i
    thousandSeparator: "."
    decimalSeparator: ","
    currencyDecimalSeparator: ","
    nullDisplay: ""
  urlManager:
     enablePrettyUrl: false
  view:
    theme: themes\bootstrap\Theme