---
components:
  request:
    cookieValidationKey: 8423c873da45b11f3a3bbbba0c4d5be3
  db:
    dsn: mysql:host=localhost;dbname=viajes
    username: root
    password: root
    charset: utf8
params:
  admin:
    name: Admin
    email: admin@mail.com
  foo:
    hola:
    - como=estas
    - tu=xyz
aliases: []
modules: []
catchAll:
- site/offline
- ::1
...
