---
components:
  request:
    cookieValidationKey: 8423c873da45b11f3a3bbbba0c4d5be3
  db:
    dsn: mysql:host=localhost;dbname=allone
    username: root
    password: root
    charset: utf8
  view:
    theme: kyubi\theme\basic\Theme
params:
  admin:
    name: Admin
    email: admin@mail.com
aliases:
  kyubi-backend: vendor/kyubi/backend
modules:
  backend:
    class: kyubi\backend\Module
...
