controllers:
  vehicle: 
     class: kyubi\api\controllers\CrudController
     config: fleet/config/models/vehicle.yaml
  planning:
navbar:
  order: 1
  links:
  - vehicle:
  - itv: "#"
  - separator
  - planning:
  - maintenance: false
  - vehicle-brand: false
  - vehicle-model: false
  - vehicle-family: false
  - vehicle-type: false
  - separator
  - vehicle-rate: false
  - vehicle-gas: false