controllers:
  vehicle:
  planning:
navbar:
  order: 1
  links:
  - url: vehicle
  - url: itv
    disabled: true
    separator: after
  - url: planning
    separator: after
  - url: maintenance
    disabled: true
  - url: vehicle-brand
    disabled: true
  - url: vehicle-model
    disabled: true
  - url: vehicle-family
    disabled: true
  - url: vehicle-type
    disabled: true
    separator: after
  - url: vehicle-rate
    disabled: true
  - url: vehicle-gas
    disabled: true