es:
  flota: Flota
  flota/vehiculo: Vehículos
  flota/itv: ITV
  flota/planeacion: Planeación
  flota/mantenimiento: Mantenimientos
  flota/marca: Marcas de vehículo
  flota/modelo: Modelos de vehículo
  flota/familia: Famílias de vehículo
  flota/tipo: Tipos de vehículo
  flota/tarifas: Grupo de tarificación
