icon: fa-user
defaultRoute: client
controllers:
  client:
    class: kyubi\api\controllers\CrudController
    modelClass: cart\models\Clients
  invoice:
  charge:
  consignment:
  accumulated:
navbar:
  order: 2
  links:
    - url: client
      separator: after
    - url: invoice
      separator: after
    - url: charge
    - url: consignment
      separator: after
    - label: reports
    - url: accumulated