icon: fa-user
defaultRoute: client
controllers:
  client:
    class: kyubi\api\controllers\CrudController
    modelClass: app\models\base\cart\Clients
    modelConfig: client/config/models/clients.yaml
  invoice:
  charge:
  consignment:
  accumulated:
navbar:
  order: 2
  links:
    - client:
    - separator
    - invoice:
    - separator
    - charge:
    - consignment:
    - separator
    - reports
    - accumulated:
    