name: Clientes
icon: fa-user
controllers:
  default:
navbar:
  label: Clientes
  order: 2
  links:
    - label: Clientes
      url: client
      separator: after
    - label: Facturas cliente
      url: invoice
      separator: after
    - label: Cobros
      url: charge
    - label: Remesas cliente
      url: consignment
      separator: after
    - label: Informes
    - label: Factura acumulada
      url: accumulated