name: Clientes
icon: fa-user
controllers:
  default:
  user:
    name: Usuario
    icon: fa-user
  role:
    name: Rol
    icon: fa-users
  profile:
    name: Perfil
    icon: fa-universal-access
navbar:
  label: Clientes
  order: 2
  links:
    - label: Clientes
      url: client
      separator: after
    - label: Facturas cliente
      url: invoice
      separator: after
    - label: Cobros
      url: charge
    - label: Remesas cliente
      url: client/clients
      separator: after
    - label: Informes
    - label: Factura acumulada
      url: accumulated