scenarios:
  default: 'nombre descripcion correo telefono'
sections:
  modelos@view:
    relation: modelos
attributes:
  nombre:
    options:
      container:
        class: col-12
  descripcion:
    options:
      input:
        class: vh-30
      container:
        class: col-12
  correo:
    type: email
    options:
      container:
        class: 'col-12 col-md-6'
  telefono:
    options:
      container:
        class: 'col-12 col-md-6'
