scenarios:
  default: 'nombre descripcion correo telefono'
attributes: ~
relations:
  modelos: 'hasMany flota\models\base\Modelo marca_id'
sections:
  modelos@view:
    relation: modelos
  'modelos@create update view':
    relation: modelos
