scenarios:
  default: 'potencia combustible combustible_cap largo ancho alto'
attributes: ~
relations:
  modelo: flota\models\base\Modelo
sections:
  'modelo@create update view':
    relation: modelo
