scenarios:
  default: 'largo ancho alto peso volumen'
attributes: ~
relations:
  modelo: flota\models\base\Modelo
sections:
  'modelo@create update view':
    relation: modelo
  modelo@view:
    relation: modelo
