scenarios:
  default: 'tipo_id marca_id nombre descripcion'
  search: 'marca.nombre nombre tipo_id descripcion'
  search-rel: 'nombre tipo_id descripcion'
relations:
  marca: 'flota\models\base\Marca marca_id'
  caracteristicas: flota\models\base\ModeloCaracteristicas
  carga: flota\models\base\ModeloCarga
  vehiculos: 'hasMany flota\models\base\Vehiculo modelo_id'
sections:
  vehiculos@view:
    relation: vehiculos
name@select: 'php:$this->marca ? ("{$this->marca->nombre} : $this->nombre" . (($tipo = $this->tipo) ? " ( $tipo->id ) - {$tipo->nombre}" : null)) : null'
attributes:
  tipo_id@view:
    value: 'php:($tipo = $this->tipo) ? "( $tipo->id ) - {$tipo->nombre}" : null'
  tipo_id:
    options:
      select:
        scenario: select
      container:
        class: 'col-12 col-sm-6 col-md-6 col-lg-8'
  marca.nombre:
    label: marca_id
    options:
      container:
        class: 'col-12 col-sm-6 col-md-6 col-lg-4'
  marca_id@view:
    value: marca.nombre
  marca_id:
    options:
      container:
        class: 'col-12 col-sm-6 col-md-6 col-lg-4'
  nombre:
    options:
      container:
        class: col-12
  descripcion:
    options:
      input:
        class: vh-30
      container:
        class: col-12
