scenarios:
  default: 'fecha_transaccion tipo_tarifa desde hasta fecha_inicio fecha_fin km eur_km eur_lt hora eur_hora eur_dia eur_mes'
sections:
  delegacion:
    relation: delegacion
  tarifa:
    relation: tarifa
  tipo:
    relation: tipo
attributes:
  fecha_transaccion: ~
