scenarios:
  default: 'delegacion_id tipo_id tipo_tarifa desde hasta fecha_inicio fecha_fin km eur_km eur_lt hora eur_hora eur_dia eur_mes'
  'search view': 'delegacion.nombre tipo_id tipo_tarifa desde hasta fecha_inicio fecha_fin km eur_km eur_lt hora eur_hora eur_dia eur_mes'
relations:
  delegacion: 'comun\models\base\Delegacion delegacion_id'
  tipo: 'flota\models\base\Tipo tipo_id'
  historias: 'hasMany flota\models\base\TarifaHistoria tarifa_id'
sections:
  historias@view:
    relation: historias
attributes:
  delegacion.nombre:
    label: delegacion_id
  tipo_id@view:
    value: 'php:($tipo = $this->tipo) ? "( $tipo->id ) - {$tipo->nombre}" : null'
  tipo_id:
    options:
      select:
        scenario: select
  fecha_inicio:
    format: date
  fecha_fin:
    format: date
  km:
    format:
      - decimal
      - 2
  eur_km:
    format:
      - decimal
      - 2
  eur_lt:
    format:
      - decimal
      - 2
  hora:
    format:
      - decimal
      - 2
  eur_hora:
    format:
      - decimal
      - 2
  eur_dia:
    format:
      - decimal
      - 2
  eur_mes:
    format:
      - decimal
      - 2
name: 'php: intval($this->desde) . ($t = lcfirst($this->tipo_tarifa[0])) . " - $this->hasta$t"'
