scenarios:
  default: 'id tipo_vehiculo nombre descripcion fianza franquicia'
sections:
  modelos@view:
    relation: modelos
  tarifas@view:
    relation: tarifas
attributes:
  fianza:
    format:
      - decimal
      - 2
    options:
      container:
        class: 'col-12 col-md-6'
  franquicia:
    format:
      - decimal
      - 2
    options:
      container:
        class: 'col-12 col-md-6'
  id:
    options:
      container:
        class: 'col-6 col-md-2'
  nombre:
    options:
      container:
        class: 'col-12 col-md-6'
  descripcion:
    options:
      input:
        class: line-2
      container:
        class: col-12
  tipo_vehiculo:
    options:
      container:
        class: 'col-6 col-md-4'
