scenarios:
  default: observacion
relations:
  vehiculo: flota\models\base\Vehiculo
attributes:
  observacion:
    options:
      container:
        class: col-12
      input:
        class: vh-50
      label:
        class: d-none
