scenarios:
  search: 'matricula, bastidor, color, fecha_matricula, modelo, delegacion, estado, fecha_estado'
  view: 'matricula, bastidor, color, fecha_matricula, modelo, delegacion, estado, fecha_estado'
attributes:
  id: null
  matricula:
    value: xyz
  bastidor: null
  color: color
  fecha_matricula: date
  gps: null
  modelo__id:
    type: relation
  delegacion__id: 
    type: select
    relation: delegacion
  estado:
    type: select
    options:
      - UNO
      - DOS
      - TRES
  ultimo_estado: null
  anio2: null
  anio: null
sections:
  datos: null
  accesorios: flota/views/vehiculo/datos
  historico: null
  gastos: null
  observacion: null
'name::view': '{matricula}HOLA'
table:
  flota__vehiculo__view: 'view, search'
