scenarios:
  default: matricula fecha_matricula bastidor modelo_id estado
  view search: matricula fecha_matricula bastidor modelo.nombre estado
attributes:
  modelo.nombre:
    label: modelo_id
relations:
  caracteristicas: flota\models\base\VehiculoCaracteristicas
  delegacions: hasMany flota\models\base\VehiculoDelegacion vehiculo_id
  ordenVehiculos: hasMany operacion\models\base\OrdenVehiculo vehiculo_id
  ordens: hasMany operacion\models\base\Orden orden_id
  movimientos: hasMany flota\models\base\VehiculoMovimiento
sections:
  caracteristicas@create update view:
    relation: caracteristicas
