scenarios:
  default: 'color anio transmision plazas puertas extra'
attributes: ~
relations:
  vehiculo: flota\models\base\Vehiculo
sections:
  'vehiculo@create update view':
    relation: vehiculo
  vehiculo@view:
    relation: vehiculo
foo:
  vehiculo:
    type: hasOne
    refClass: flota\models\base\Vehiculo
    refColumn: id
    column: id
