scenarios:
  default: 'matricula fecha_matricula bastidor estado modelo_id'
attributes: ~
relations:
  caracteristicas: flota\models\base\VehiculoCaracteristicas
  delegacions: 'hasMany flota\models\base\VehiculoDelegacion vehiculo_id'
  ordenVehiculos: 'hasMany operacion\models\base\OrdenVehiculo vehiculo_id'
  ordens: 'hasMany operacion\models\base\Orden orden_id ordenVehiculos'
  movimientos: 'hasMany flota\models\base\VehiculoMovimiento'
sections:
  'caracteristicas@create update view':
    relation: caracteristicas
  delegacions@view:
    relation: delegacions
  orden-vehiculos@view:
    relation: ordenVehiculos
  ordens@view:
    relation: ordens
  movimientos@view:
    relation: movimientos
