scenarios:
  default: 'matricula fecha_matricula bastidor estado modelo_id'
attributes: ~
relations: ~
sections:
  'caracteristicas@create update view':
    relation: caracteristicas
  'delegacions@create update view':
    relation: delegacions
  'orden-vehiculos@create update view':
    relation: ordenVehiculos
  'ordens@create update view':
    relation: ordens
  'movimientos@create update view':
    relation: movimientos
