scenarios:
  default: 'matricula fecha_matricula bastidor modelo_id'
  search: 'matricula fecha_matricula bastidor modelo.nombre situacion.estado'
  search-rel: 'matricula fecha_matricula bastidor situacion.fecha_estado situacion.estado'
sections:
  situacion:
    relation: situacion
  historias@view:
    relation: historias
  caracteristicas:
    relation: caracteristicas
  observacion:
    relation: observacion
attributes:
  modelo.nombre:
    label: modelo_id
    options:
      container:
        class: 'col-12 col-md-6 col-lg-8'
  modelo_id@view:
    value: 'php:(($marca = $this->modelo->marca) ? "$marca->nombre : " : null ) . (($modelo = $this->modelo) ? ($modelo->nombre . (($tipo = $modelo->tipo) ? " ( {$tipo->id} ) - {$tipo->nombre}" : null)) : null)'
  modelo_id:
    relation:
      name: 'php:(($marca = $this->marca) ? ($marca->nombre . " : ") : null) . $this->nombre . (($tipo = $this->tipo) ? " ( {$tipo->id} ) - {$tipo->nombre}" : null)'
    options:
      container:
        class: col-12
