scenarios:
  default: 'nombre descripcion correo telefono whatsapp'
attributes: ~
relations:
  comunOficinas: 'hasmany app\models\base\ComunOficina delegacion_id'
  flotaTarifaHistoricos: 'hasMany app\models\base\FlotaTarifaHistorico delegacion_id'
  flotaTarifas: 'hasMany app\models\base\FlotaTarifa delegacion_id'
  flotaVehiculoDelegacions: 'hasmany app\models\base\FlotaVehiculoDelegacion delegacion_id'
  flotaVehiculos: 'hasmany app\models\base\FlotaVehiculo vehiculo_id flotaVehiculoDelegacions'
sections:
  comun-oficinas@view:
    relation: comunOficinas
  flota-tarifa-historicos@view:
    relation: flotaTarifaHistoricos
  flota-tarifas@view:
    relation: flotaTarifas
  flota-vehiculo-delegacions@view:
    relation: flotaVehiculoDelegacions
  'comun-oficinas@create update view':
    relation: comunOficinas
  'flota-vehiculo-delegacions@create update view':
    relation: flotaVehiculoDelegacions
  'flota-vehiculos@create update view':
    relation: flotaVehiculos
