scenarios:
  default: 'nombre descripcion fecha combustible km estado contrato_numero vehiculo_id'
attributes: ~
relations:
  flotaVehiculo: 'app\models\base\FlotaVehiculo vehiculo_id'
  operacionDocument: 'app\models\base\OperacionDocument codigo contrato_numero'
  operacionOrdenMovimientos: 'hasMany app\models\base\OperacionOrdenMovimiento movimiento_id'
sections:
  'flota-vehiculo@create update view':
    relation: flotaVehiculo
  'operacion-document@create update view':
    relation: operacionDocument
  operacion-orden-movimientos@view:
    relation: operacionOrdenMovimientos
