scenarios:
  default: 'nombre descripcion correo telefono'
attributes: ~
relations:
  flotaModelos: 'hasmany app\models\base\FlotaModelo marca_id'
sections:
  flota-modelos@view:
    relation: flotaModelos
  'flota-modelos@create update view':
    relation: flotaModelos
