scenarios:
  default: 'desde hasta tipo_tarifa fecha_inicio fecha_fin km eur_km lt eur_lt hora eur_hora dia eur_dia tipo_id delegacion_id'
attributes: ~
relations:
  comunDelegacion: 'app\models\base\ComunDelegacion delegacion_id'
  flotaTipo: 'app\models\base\FlotaTipo tipo_id'
  historicos: 'hasMany app\models\base\FlotaTarifaHistorico tarifa_id'
sections:
  'comun-delegacion@create update view':
    relation: comunDelegacion
  'flota-tipo@create update view':
    relation: flotaTipo
  historicos@view:
    relation: historicos
