scenarios:
  default: 'potencia combustible combustible_cap largo ancho alto'
attributes: ~
relations:
  flotaModelo: app\models\base\FlotaModelo
sections:
  'flota-modelo@create update view':
    relation: flotaModelo
