scenarios:
  default: 'tipo_contrato tarifa_id fecha_entrega fecha_recogida cliente_id'
attributes: ~
relations:
  comunCliente: 'app\models\base\ComunCliente cliente_id'
  tarifaTarifa: 'app\models\base\TarifaTarifa tarifa_id'
  operacionMomentoOrdens: 'hasMany app\models\base\OperacionMomentoOrden orden_id'
  vehiculos: 'hasmany app\models\base\OperacionOrdenVehiculo orden_id'
  flotaVehiculos: 'hasmany app\models\base\FlotaVehiculo vehiculo_id operacionOrdenVehiculos'
  operacionDocuments: 'hasmany app\models\base\OperacionDocument document_id operacionOrdenDocuments'
  documents: 'hasmany app\models\base\OperacionOrdenDocument orden_id'
sections:
  'comun-cliente@create update view':
    relation: comunCliente
  'tarifa-tarifa@create update view':
    relation: tarifaTarifa
  operacion-momento-ordens@view:
    relation: operacionMomentoOrdens
  vehiculos@view:
    relation: vehiculos
  'flota-vehiculos@create update view':
    relation: flotaVehiculos
  'operacion-documents@create update view':
    relation: operacionDocuments
  'documents@create update view':
    relation: documents
  'vehiculos@create update view':
    relation: vehiculos
