scenarios:
  default: 'orden_id vehiculo_id'
attributes: ~
relations:
  flotaVehiculo: 'app\models\base\FlotaVehiculo vehiculo_id'
  operacionOrden: 'app\models\base\OperacionOrden orden_id'
  operacionOrdenMovimientos: 'hasMany app\models\base\OperacionOrdenMovimiento orden_vehiculo_id'
sections:
  'flota-vehiculo@create update view':
    relation: flotaVehiculo
  'operacion-orden@create update view':
    relation: operacionOrden
  operacion-orden-movimientos@view:
    relation: operacionOrdenMovimientos
