scenarios:
  default: 'codigo tipo estado document_id'
attributes: ~
relations:
  flotaVehiculoMovimientos: 'hasmany app\models\base\FlotaVehiculoMovimiento documento_codigo codigo'
  s: 'hasmany app\models\base\OperacionDocument document_id'
  operacionOrdenDocuments: 'hasmany app\models\base\OperacionOrdenDocument document_id'
  operacionOrdens: 'hasmany app\models\base\OperacionOrden orden_id operacionOrdenDocuments'
sections:
  'flota-vehiculo-movimientos@create update view':
    relation: flotaVehiculoMovimientos
  's@create update view':
    relation: s
  'operacion-orden-documents@create update view':
    relation: operacionOrdenDocuments
  'operacion-ordens@create update view':
    relation: operacionOrdens
