scenarios:
  default: 'hasta tipo_tarifa periodo_id'
attributes: ~
relations:
  operacionOrdens: 'hasmany app\models\base\OperacionOrden tarifa_id'
  tarifaItems: 'hasmany app\models\base\TarifaItem item_id tarifaTarifaItems'
  historicos: 'hasMany app\models\base\TarifaTarifaHistorico tarifa_id'
  periodos: 'hasMany app\models\base\TarifaTarifaPeriodo tarifa_id'
  tipos: 'hasMany app\models\base\TarifaTarifaTipo tarifa_id'
  tarifaGrupoTarifas: 'hasmany app\models\base\TarifaGrupoTarifa tarifa_id'
  tarifaGrupos: 'hasmany app\models\base\TarifaGrupo grupo_id tarifaGrupoTarifas'
  items: 'hasmany app\models\base\TarifaTarifaItem tarifa_id'
sections:
  operacion-ordens@view:
    relation: operacionOrdens
  tarifa-items@view:
    relation: tarifaItems
  historicos@view:
    relation: historicos
  periodos@view:
    relation: periodos
  tipos@view:
    relation: tipos
  'operacion-ordens@create update view':
    relation: operacionOrdens
  'tarifa-grupo-tarifas@create update view':
    relation: tarifaGrupoTarifas
  'tarifa-grupos@create update view':
    relation: tarifaGrupos
  'tarifa-items@create update view':
    relation: tarifaItems
  'items@create update view':
    relation: items
