scenarios:
  default: 'id nombre descripcion tipo_vehiculo fianza franquicia'
attributes: ~
relations:
  flotaModelos: 'hasmany app\models\base\FlotaModelo modelo_id tarifaGrupoModelos'
  modelos: 'hasmany app\models\base\TarifaGrupoModelo grupo_id'
  tarifas: 'hasmany app\models\base\TarifaGrupoTarifa grupo_id'
  tarifaTarifas: 'hasmany app\models\base\TarifaTarifa tarifa_id tarifaGrupoTarifas'
sections:
  'flota-modelos@create update view':
    relation: flotaModelos
  'modelos@create update view':
    relation: modelos
  'tarifas@create update view':
    relation: tarifas
  'tarifa-tarifas@create update view':
    relation: tarifaTarifas
