scenarios:
  default: 'nombre descripcion tarifa cantidad magnitud tipo'
attributes: ~
relations:
  tarifaTarifa: 'app\models\base\TarifaTarifa tarifa_id'
  historicos: 'hasMany app\models\base\TarifaItemHistorico item_id'
  tarifaTarifaItems: 'hasmany app\models\base\TarifaTarifaItem item_id'
  tarifaTarifas: 'hasmany app\models\base\TarifaTarifa tarifa_id tarifaTarifaItems'
sections:
  'tarifa-tarifa@create update view':
    relation: tarifaTarifa
  historicos@view:
    relation: historicos
  'tarifa-tarifa-items@create update view':
    relation: tarifaTarifaItems
  'tarifa-tarifas@create update view':
    relation: tarifaTarifas
