---
es:
  index: <i class="fa fa-list-alt"></i> Listar
  create: <i class="fa fa-plus"></i> Nuevo
  update: <i class="fa fa-pencil"></i> Editar
  view: <i class="fa fa-eye"></i> Mostrar
  delete: <i class="fa fa-trash"></i> Eliminar
  Save all: <i class="fa fa-save"></i> Guardar todo
  # [Header content]
  '{controller}': '{controller}'
  '{action} {controller}': '{controller} <small>{action}</small>'
  '{action} {controller} {model}': '{controller} <strong>{model}</strong> <small>{action}</small>'
  'create {controller}': 'Nuevo registro <small><i class="fa fa-plus text-success"></i></small>'
  'view {controller} {model}': '<strong>{model}</strong>'
  'update {controller} {model}': '<strong>{model}</strong> <small><i class="fa fa-pencil text-warning"></i></small>'
  # [Other content]
  "Select option": ---
...