scenarios:
  default: 'tipo observacion'
attributes: ~
relations:
  persona: comun\models\base\Persona
  conductors: 'hasMany comun\models\base\Conductor conductor_id'
  ordens: 'hasMany operacion\models\base\Orden cliente_id'
sections:
  'persona@create update view':
    relation: persona
  conductors@view:
    relation: conductors
  ordens@view:
    relation: ordens
