scenarios:
  default: 'carnet carnet_pais fecha_expedicion fecha_vencimiento'
attributes: ~
relations:
  persona: comun\models\base\Persona
  clienteConductors: 'hasMany comun\models\base\ClienteConductor conductor_id'
  clientes: 'hasMany comun\models\base\Cliente cliente_id'
sections:
  cliente-conductors@view:
    relation: clienteConductors
  'persona@create update view':
    relation: persona
  clientes@view:
    relation: clientes
