scenarios:
  default: 'carnet carnet_pais fecha_expedicion fecha_vencimiento'
attributes: ~
relations:
  persona: comun\models\base\Persona
  clienteConductors: 'hasMany comun\models\base\ClienteConductor conductor_id'
  clientes: 'hasMany comun\models\base\Cliente cliente_id clienteConductors'
sections:
  'persona@create update view':
    relation: persona
  'cliente-conductors@create update view':
    relation: clienteConductors
  'clientes@create update view':
    relation: clientes
  cliente-conductors@view:
    relation: clienteConductors
  clientes@view:
    relation: clientes
