scenarios:
  default: 'nombre descripcion correo telefono whatsapp'
sections:
  oficinas@view:
    relation: oficinas
  orden-historias@view:
    relation: ordenHistorias
  ordens@view:
    relation: ordens
  tarifa-historias@view:
    relation: tarifaHistorias
  tarifas@view:
    relation: tarifas
  vehiculo-historias@view:
    relation: vehiculoHistorias
  vehiculo-situacions@view:
    relation: vehiculoSituacions
  vehiculos@view:
    relation: vehiculos
