scenarios:
  default: 'nombre descripcion correo telefono whatsapp'
sections:
  oficinas@view:
    relation: oficinas
  ordens@view:
    relation: ordens
  tarifas@view:
    relation: tarifas
  vehiculo-situacions@view:
    relation: vehiculoSituacions
  vehiculos@view:
    relation: vehiculos
attributes:
  nombre:
    options:
      container:
        class: col-12
  descripcion:
    options:
      input:
        class: line-2
      container:
        class: col-12
