scenarios:
  default: 'nombre descripcion correo telefono whatsapp'
attributes: ~
relations:
  oficinas: 'hasMany comun\models\base\Oficina delegacion_id'
  vehiculoDelegacions: 'hasMany flota\models\base\VehiculoDelegacion delegacion_id'
  vehiculos: 'hasMany flota\models\base\Vehiculo vehiculo_id vehiculoDelegacions'
sections:
  oficinas@view:
    relation: oficinas
  vehiculo-delegacions@view:
    relation: vehiculoDelegacions
  vehiculos@view:
    relation: vehiculos
  'oficinas@create update view':
    relation: oficinas
  'vehiculo-delegacions@create update view':
    relation: vehiculoDelegacions
  'vehiculos@create update view':
    relation: vehiculos
