scenarios:
  default: 'nombre descripcion direccion horario ubicacion correo telefono whatsapp delegacion_id'
attributes: ~
relations:
  delegacion: 'comun\models\base\Delegacion delegacion_id'
sections:
  'delegacion@create update view':
    relation: delegacion
