scenarios:
  default: 'nombre dni pais_dni nacionalidad fecha_nacimiento'
attributes: ~
relations:
  cliente: comun\models\base\Cliente
  conductor: comun\models\base\Conductor
  contactos: 'hasMany comun\models\base\PersonaContacto persona_id'
  direccions: 'hasMany comun\models\base\PersonaDireccion persona_id'
sections:
  'cliente@create update view':
    relation: cliente
  'conductor@create update view':
    relation: conductor
  contactos@view:
    relation: contactos
  direccions@view:
    relation: direccions
