scenarios:
  default: 'nombre dni pais_dni nacionalidad fecha_nacimiento'
attributes: ~
relations:
  cliente: comun\models\base\Cliente
  conductor: comun\models\base\Conductor
  contactos: 'hasmany comun\models\base\PersonaContacto persona_id'
  direccions: 'hasmany comun\models\base\PersonaDireccion persona_id'
  personaContactos: 'hasMany comun\models\base\PersonaContacto persona_id'
  personaDireccions: 'hasMany comun\models\base\PersonaDireccion persona_id'
sections:
  'cliente@create update view':
    relation: cliente
  'conductor@create update view':
    relation: conductor
  contactos@view:
    relation: contactos
  direccions@view:
    relation: direccions
  cliente@view:
    relation: cliente
  conductor@view:
    relation: conductor
  'contactos@create update view':
    relation: contactos
  'direccions@create update view':
    relation: direccions
  'persona-contactos@create update view':
    relation: personaContactos
  'persona-direccions@create update view':
    relation: personaDireccions
  persona-contactos@view:
    relation: personaContactos
  persona-direccions@view:
    relation: personaDireccions
