es:
  name: Operaciones
  operacion/presupuesto: Presupuesto
  operacion/reserva: Reserva
  operacion/contrato: Contrato
  #
  'create {controller}': '{controller} <span class="btn btn-sm btn-success">Nuevo</span>'
  