scenarios:
  default: 'nombre descripcion tarifa cantidad magnitud tipo'
attributes: ~
relations:
  tarifaItems: 'hasMany tarifa\models\base\TarifaItem item_id'
  tarifas: 'hasMany tarifa\models\base\Tarifa tarifa_id tarifaItems'
sections:
  tarifa-items@view:
    relation: tarifaItems
  tarifas@view:
    relation: tarifas
