scenarios:
  default: 'hasta tipo_tarifa periodo_id'
attributes: ~
relations:
  periodo: 'tarifa\models\base\Periodo periodo_id'
  items: 'hasMany tarifa\models\base\TarifaItem tarifa_id'
  ordens: 'hasMany operacion\models\base\Orden tarifa_id'
  tipos: 'hasMany flota\models\base\Tipo grupo_id'
sections:
  'periodo@create update view':
    relation: periodo
  items@view:
    relation: items
  ordens@view:
    relation: ordens
  tipos@view:
    relation: tipos
