scenarios:
  default: 'delegacion_id cliente tipo_contrato tipo_id tipo_tarifa momento estado codigo orden_id'
sections:
  delegacion:
    relation: delegacion
  '':
    relation: ''
  tipo:
    relation: tipo
  historias@view:
    relation: historias
  s@view:
    relation: s
