scenarios:
  default: 'tipo_contrato tarifa_id fecha_entrega fecha_recogida cliente_id'
attributes: ~
relations:
  documents: 'hasMany operacion\models\base\OrdenDocument orden_id'
  vehiculos: 'hasMany flota\models\base\Vehiculo vehiculo_id'
sections:
  documents@view:
    relation: documents
  vehiculos@view:
    relation: vehiculos
