scenarios:
  default: 'tipo_contrato tarifa_id fecha_entrega fecha_recogida cliente_id'
attributes: ~
relations:
  cliente: 'comun\models\base\Cliente cliente_id'
  tarifa: 'tarifa\models\base\Tarifa tarifa_id'
  momentoOrdens: 'hasMany operacion\models\base\MomentoOrden orden_id'
  vehiculos: 'hasMany flota\models\base\Vehiculo vehiculo_id'
  documents: 'hasMany operacion\models\base\OrdenDocument orden_id'
sections:
  'cliente@create update view':
    relation: cliente
  'tarifa@create update view':
    relation: tarifa
  momento-ordens@view:
    relation: momentoOrdens
  vehiculos@view:
    relation: vehiculos
  documents@view:
    relation: documents
