scenarios:
  default: 'vehiculo_matricula km combustible detalle'
attributes:
  vehiculo_matricula:
    relation:
      id: matricula
      name: matricula
  detalle:
    options:
      input:
        class: line-2
      container:
        class: col-12
