scenarios:
  default: 'delegacion_id cliente tipo_contrato tipo_id tipo_tarifa momento estado codigo orden_id'
sections:
  delegacion:
    relation: delegacion
  orden:
    relation: orden
  tipo:
    relation: tipo
  historias@view:
    relation: historias
  tarifas@view:
    relation: tarifas
  ordens@view:
    relation: ordens
  vehiculo-historias@view:
    relation: vehiculoHistorias
