scenarios:
  default: 'fecha hora km combustible descripcion'
attributes:
  fecha:
    options:
      container:
        class: 'col-6 col-md-3'
  hora:
    options:
      container:
        class: 'col-6 col-md-3'
  km:
    format:
      - decimal
      - 2
    options:
      container:
        class: 'col-6 col-md-3'
  combustible:
    format:
      - decimal
      - 2
    options:
      container:
        class: 'col-6 col-md-3'
  descripcion:
    options:
      input:
        class: line-2
      container:
        class: col-12
